name: priyopabna
description: A new Flutter project.
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  awesome_dialog: ^2.1.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^3.1.10
  dots_indicator: ^2.0.0
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  fontisto_flutter: ^3.1.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^0.8.2
  share: ^2.0.4
  url_launcher: ^6.0.20
  google_mobile_ads: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/icons/

  fonts:
    - family: lobster
      fonts:
        - asset: assets/fonts/lobster-regular.ttf
    - family: lobster
      fonts:
        - asset: assets/fonts/lobster-regular.ttf
